/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//By Prashant Rana 2300680140090
package calculator2;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class cal extends javax.swing.JFrame {

    /**
     * Creates new form cal
     */
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        output = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        pow = new javax.swing.JButton();
        eql = new javax.swing.JButton();
        ac = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(null);
        setResizable(false);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        num1.setPreferredSize(new java.awt.Dimension(96, 33));
        main.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 200, 25));

        num2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        num2.setPreferredSize(new java.awt.Dimension(96, 33));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        main.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 63, 200, 25));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("by/with");
        main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 37, 73, 20));

        output.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        main.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 120, 200, 25));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Output");
        main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, -1, 20));

        add.setBackground(new java.awt.Color(255, 204, 0));
        add.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("+");
        add.setToolTipText("");
        add.setBorder(null);
        add.setPreferredSize(new java.awt.Dimension(40, 35));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        main.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 25));

        sub.setBackground(new java.awt.Color(255, 204, 0));
        sub.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        sub.setForeground(new java.awt.Color(255, 255, 255));
        sub.setText("-");
        sub.setToolTipText("");
        sub.setBorder(null);
        sub.setPreferredSize(new java.awt.Dimension(40, 35));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        main.add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 25));

        mul.setBackground(new java.awt.Color(255, 204, 0));
        mul.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        mul.setForeground(new java.awt.Color(255, 255, 255));
        mul.setText("*");
        mul.setToolTipText("");
        mul.setBorder(null);
        mul.setPreferredSize(new java.awt.Dimension(40, 35));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });
        main.add(mul, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, 25));

        div.setBackground(new java.awt.Color(255, 204, 0));
        div.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("/");
        div.setToolTipText("");
        div.setBorder(null);
        div.setPreferredSize(new java.awt.Dimension(40, 35));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        main.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, 25));

        mod.setBackground(new java.awt.Color(255, 204, 0));
        mod.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        mod.setForeground(new java.awt.Color(255, 255, 255));
        mod.setText("%");
        mod.setToolTipText("");
        mod.setBorder(null);
        mod.setPreferredSize(new java.awt.Dimension(45, 35));
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });
        main.add(mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 40, 25));

        pow.setBackground(new java.awt.Color(255, 204, 0));
        pow.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pow.setForeground(new java.awt.Color(255, 255, 255));
        pow.setText("^");
        pow.setToolTipText("");
        pow.setBorder(null);
        pow.setPreferredSize(new java.awt.Dimension(40, 35));
        pow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powActionPerformed(evt);
            }
        });
        main.add(pow, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 25));

        eql.setBackground(new java.awt.Color(255, 204, 0));
        eql.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        eql.setForeground(new java.awt.Color(255, 255, 255));
        eql.setText("=");
        eql.setToolTipText("");
        eql.setBorder(null);
        eql.setPreferredSize(new java.awt.Dimension(35, 35));
        eql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eqlActionPerformed(evt);
            }
        });
        main.add(eql, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 40, 25));

        ac.setBackground(new java.awt.Color(255, 204, 0));
        ac.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ac.setForeground(new java.awt.Color(255, 255, 255));
        ac.setText("AC");
        ac.setToolTipText("");
        ac.setBorder(null);
        ac.setPreferredSize(new java.awt.Dimension(40, 40));
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        main.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\orange.png")); // NOI18N
        main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 350, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
        num1.setText("");
        num2.setText("");
        output.setText("");
    }//GEN-LAST:event_acActionPerformed

    private void eqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eqlActionPerformed
        // TODO add your handling code here:
        if(output.getText().length()>0){
            String op = output.getText();
            num1.setText("");
            num1.setText(op);
            output.setText("");
        }
    }//GEN-LAST:event_eqlActionPerformed

    private void powActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powActionPerformed
        // TODO add your handling code here:
        if(num1.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter Number");
        }
        else if(num2.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter Power");
        }else
        {
            double n1 = Double.parseDouble(num1.getText());
            int n2 = Integer.parseInt(num2.getText());
            double opw=1;
            for(int i = 0;i<n2;i++){
                opw = opw*n1;
            }
            String opwstr = Double.toString(opw);
            output.setText("");
            output.setText(opwstr);
        }
    }//GEN-LAST:event_powActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
        // TODO add your handling code here:\ int n1 = Integer.parseInt(num1.getText());
        if(num1.getText().length()==0 && num2.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter First Number");
        }
        else if(num1.getText().length()>0&&num2.getText().length()==0){
            double n = Double.parseDouble(num1.getText());
            double mod = n/100;
            String modstr = Double.toString(mod);
            output.setText("");
            output.setText(modstr);
        }
        else if(num1.getText().length()==0&&num2.getText().length()>0){
            double n = Double.parseDouble(num2.getText());;
            double mod = n/100;
            String modstr = Double.toString(mod);
            output.setText("");
            output.setText(modstr);
        }
        else if(num1.getText().length()>0&&num2.getText().length()>0){
            double n1 = Double.parseDouble(num1.getText());
            double n2 = Double.parseDouble(num2.getText());
            if(n1<=0||n2<=0){
                output.setText("");
                output.setText("Error");
            }else{
                double mod2 = n1%n2;
                String mod2str = Double.toString(mod2);
                output.setText("");
                output.setText(mod2str);
            }
        }
    }//GEN-LAST:event_modActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
        if(num1.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter first Numebr");
        }
        else if(num2.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter Second Number");
        }else if("0".equals(num2.getText())){
            output.setText("Error");

        }else{
            double n1 = Double.parseDouble(num1.getText());
            double n2 = Double.parseDouble(num2.getText());
            double div = n1/n2;
            String divstr = Double.toString(div);
            output.setText("");
            output.setText(divstr);
        }
    }//GEN-LAST:event_divActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        double n1 = Double.parseDouble(num1.getText());
        double n2 = Double.parseDouble(num2.getText());
        double sub = n1-n2;
        String substr = Double.toString(sub);
        output.setText("");
        output.setText(substr);
    }//GEN-LAST:event_subActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(num1.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter first Numebr");
        }
        else if(num2.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter Second Number");
        }else
        {
            double n1 = Double.parseDouble(num1.getText());
            double n2 = Double.parseDouble(num2.getText());
            double sum = n1+n2;
            String sumstr = Double.toString(sum);
            output.setText("");
            output.setText(sumstr);
        }
    }//GEN-LAST:event_addActionPerformed

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        // TODO add your handling code here:
        if(num1.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter first Numebr");
        }
        else if(num2.getText().length()==0)
        {
            JOptionPane.showMessageDialog(this,"Enter Second Number");
        }else
        {
            double n1 = Double.parseDouble(num1.getText());
            double n2 = Double.parseDouble(num2.getText());
            double mul = n1*n2;
            String mulstr = Double.toString(mul);
            output.setText("");
            output.setText(mulstr);
        }
    }//GEN-LAST:event_mulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ac;
    private javax.swing.JButton add;
    private javax.swing.JButton div;
    private javax.swing.JButton eql;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    private javax.swing.JButton mod;
    private javax.swing.JButton mul;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField output;
    private javax.swing.JButton pow;
    private javax.swing.JButton sub;
    // End of variables declaration//GEN-END:variables
}
